improve compatibility with eslint@9
remithomas/eslint-plugin-ban pull request #31
Opened 2024-10-16 20:18 UTC by dartess

strictly speaking, the plugin is compatible with eslint@9 and flat config right now. however,

a) this is not reflected in the docs
b) the plugin lacks new fields in "meta" that eslint needs for best caching
c) this was not covered by tests (it was not clear whether the breaking changes affected you)

2024-10-17 00:11 UTC, remithomas requested changes
Thank you for PR, I'm gonna do an other round on this. But definitely it will be merged soon. 
Thanks a lot 🤩

2024-10-17 00:11 UTC, remithomas commented on package.json
> +  "version": "1.7.0",
It should be a major version. `2.0.0`

2024-10-17 00:11 UTC, remithomas commented on package.json
> +    "eslint-9": "npm:eslint@^9.0.0",
because your commit will be a major version, I recommend to upgrade only the `eslint`

2024-10-17 00:11 UTC, remithomas commented on README.md
We may want to display the current version of eslint to use, or something like that.

```md
Works with eslint >=9 for older version please use `eslint-plugin-ban` version `1.6.0`
```

2024-10-17 05:34 UTC, dartess commented
@remithomas it was fast :)

Actually, I'm not sure it's necessary. eslint@9 supports both formats, flat (default) and legacy. Also, the rule code (_now_) doesn't contain any eslint@9-specific code. So technically the package will still be compatible with all old versions of eslint. All we get by increasing the major and completely forgetting about the old eslint is the ability to remove overengineering with tests with a clear conscience.

On the other hand, eslint<9 is officially deprecated now, and maybe your suggestion makes sense.

Let me clarify once again - should we leave it like this or burn our bridges?

2024-10-18 02:32 UTC, dartess commented
@remithomas https://github.com/remithomas/eslint-plugin-ban/pull/32 opened a new PR according to the comments. ready to make changes to any of them at your choice.

2024-12-12 02:30 UTC, closed without merging